# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Ogre::BetaGUI
version:      0.01
version_from: lib/Ogre/BetaGUI.pm
installdirs:  site
requires:
    Ogre:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.36
